mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: '$(arg mqtt_bridge_ip)'
    port: '$(arg mqtt_bridge_port)'
    keepalive: 60
  private_path: device/001
# Default is json serialiser, msgpack is more efficient
serializer: json:dumps
deserializer: json:loads
bridge:

# Dynamic Bridge Server: This server should almost always be enabled as it
# responds to RemoteServer requests, and also facilitates the PublishBridge
# and the SubscribeBridge from the respective remote sides
  - factory: mqtt_bridge.bridge:DynamicBridgeServer
    control_topic: '$(arg control_topic)'
