#ns = ns or "model"+frame_id.replace('_link','')

mesh_list:
# - frame_id: test
#   ns: model_test
#   type: SHAPE
#   details:
#     position:
#       x: 0
#       y: 0
#       z: 0
#     orientation:
#       x: 0
#       y: 0
#       z: 0
#     scale:
#       x: 0
#       y: 0
#       z: 0
#     color:
#       r: 0
#       g: 0
#       b: 0

- frame_id: base_link
  type: CYLINDER
  details:
    position:
      y: 0.0456
    scale:
      x: 0.35
      y: 0.03
      z: 0.35

- frame_id: camera_rgb_frame
  ns: model_kinect_1
  type: CYLINDER
  details:
    position:
      y: 0.0817
    rotation:
      x: 90
    scale:
      x: 0.05
      y: 0.015
      z: 0.05

- frame_id: camera_rgb_frame
  ns: model_kinect_2
  type: CUBE
  details:
    position:
      y: 0.0197
    scale:
      x: 0.125
      y: 0.05
      z: 0.03

- frame_id: camera_rgb_frame
  ns: model_kinect_3
  type: CYLINDER
  details:
    position:
      y: -0.0412
    rotation:
      x: 90
    scale:
      x: 0.05
      y: 0.015
      z: 0.05

- frame_id: caster_back_link
  type: SPHERE
  details:
    scale:
      x: 0.05
      y: 0.05
      z: 0.05

- frame_id: caster_front_link
  type: SPHERE
  details:
    scale:
      x: 0.05
      y: 0.05
      z: 0.05

- frame_id: mount_xtion_pro_link
  type: CUBE
  details:
    position:
      y: 0.0116
    scale:
      x: 0.25
      y: 0.01
      z: 0.025

- frame_id: plate_bottom_link
  type: CYLINDER
  details:
    position:
      y: 0.0116
    scale:
      x: 0.25
      y: 0.01
      z: 0.025

- frame_id: plate_middle_link
  type: CYLINDER
  details:
    position:
      y: 0.0116
    scale:
      x: 0.25
      y: 0.01
      z: 0.025

- frame_id: plate_top_link
  type: CYLINDER
  details:
    position:
      y: 0.0116
    scale:
      x: 0.25
      y: 0.01
      z: 0.025

- frame_id: pole_bottom_0_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.0275
      z: 0.01

- frame_id: pole_bottom_1_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.0275
      z: 0.01

- frame_id: pole_bottom_2_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.0275
      z: 0.01

- frame_id: pole_bottom_3_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.0275
      z: 0.01

- frame_id: pole_bottom_4_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.0275
      z: 0.01

- frame_id: pole_bottom_5_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.0275
      z: 0.01

- frame_id: pole_kinect_0_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.05
      z: 0.01

- frame_id: pole_kinect_1_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.05
      z: 0.01

- frame_id: pole_kinect_1_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.05
      z: 0.01

- frame_id: pole_middle_0_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.03
      z: 0.01

- frame_id: pole_middle_1_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.03
      z: 0.01

- frame_id: pole_middle_2_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.03
      z: 0.01

- frame_id: pole_middle_3_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.03
      z: 0.01

- frame_id: pole_top_0_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.105
      z: 0.01

- frame_id: pole_top_1_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.105
      z: 0.01

- frame_id: pole_top_2_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.105
      z: 0.01

- frame_id: pole_top_3_link
  type: CYLINDER
  details:
    scale:
      x: 0.01
      y: 0.105
      z: 0.01

- frame_id: wheel_right_link
  type: CYLINDER
  details:
    rotation:
      z: 90
    scale:
      x: 0.075
      y: 0.015
      z: 0.075

- frame_id: wheel_left_link
  type: CYLINDER
  details:
    rotation:
      z: 90
    scale:
      x: 0.075
      y: 0.015
      z: 0.075

