displays:
  - visualization: Image
    reference: /camera/rgb/image_raw
    details:
      display: 1
#  - visualization: Image
#    reference: /camera/depth/image_raw
#    details:
#      normalize_range: True
#      display: 2

  - visualization: Laserscan
    reference: /scan
    details:
      style: points
      size: 3
      alpha: 1
      decay_time: 10
      flat_colour: 255,0,0

  - visualization: Map
    reference: /map
    details:
      color_scheme: raw  # map, costmap, raw
#  - visualization: Map
#    reference: /move_base/global_costmap/costmap
#  - visualization: Map
#    reference: /move_base/local_costmap/costmap

  - visualization: Odometry
    reference: /odom
    details:
      shape: arrow  # arrow, axis
      #position_tolerance: 0.1 #0.001 for smooth
      #angule_tolerance: 0.1 #0.001 for smooth

  - visualization: Path
    reference: /move_base/NavfnROS/plan
    details:
      flat_colour: 0,0,255
      alpha: 1
#  - visualization: Path
#    reference: /move_base/DWAPlannerROS/local_plan
#  - visualization: Path
#    reference: /move_base/DWAPlannerROS/global_plan

  - visualization: PointCloud2
    reference: /camera/depth/points
    details:
      style: points  # points, squares, flat_squares, spheres, boxes
      size: 1
      alpha: 0.2
      decay_time: 0
#  - visualization: PointCloud2
#    reference: /move_base/DWAPlannerROS/trajectory_cloud
#  - visualization: PointCloud2
#    reference: /move_base/DWAPlannerROS/cost_cloud

#  - visualization: Polygon
#    reference: /move_base/global_costmap/footprint
#  - visualization: Polygon
#    reference: /move_base/local_costmap/footprint

  - visualization: Pose
    reference: /move_base/current_goal
    details:
      shape: arrow
      colour: 255,0,0

  - visualization: PoseArray
    reference: /particle_cloud
    details:
      shape: arrow_flat  # we should only need this one
      flat_colour: 255,0,0

  - visualization: RobotModel
    reference: /robot_description #we use topic but really this is a param
