displays:
  - visualization: Image
    reference: /camera/rgb/image_raw
    topic_details:
      frequency: 1
    display_details:
      display: 1
      normalize_range: True
#  - visualization: Image
#    reference: /camera/depth/image_raw

  - visualization: Laserscan
    reference: /scan
    display_details:
      style: points
      size: 3
      alpha: 1
      decay_time: 10
      flat_colour: 255,0,0

  - visualization: Map
    reference: /map
    display_details:
      color_scheme: raw  # map, costmap, raw
#  - visualization: Map
#    reference: /move_base/global_costmap/costmap
#  - visualization: Map
#    reference: /move_base/local_costmap/costmap

  - visualization: Odometry
    reference: /odom
    display_details:
      shape: arrow  # arrow, axis
      #position_tolerance: 0.1 #0.001 for smooth
      #angule_tolerance: 0.1 #0.001 for smooth

  - visualization: Path
    reference: /move_base/NavfnROS/plan
    mqtt_details:
      latched: true
    display_details:
      flat_colour: 0,0,255
      alpha: 1
#  - visualization: Path
#    reference: /move_base/DWAPlannerROS/local_plan
#  - visualization: Path
#    reference: /move_base/DWAPlannerROS/global_plan

  - visualization: PointCloud2
    reference: /camera/depth/points
    display_details:
      style: points  # points, squares, flat_squares, spheres, boxes
      size: 1
      alpha: 0.2
      decay_time: 0
#  - visualization: PointCloud2
#    reference: /move_base/DWAPlannerROS/trajectory_cloud
#  - visualization: PointCloud2
#    reference: /move_base/DWAPlannerROS/cost_cloud

#  - visualization: Polygon
#    reference: /move_base/global_costmap/footprint
#  - visualization: Polygon
#    reference: /move_base/local_costmap/footprint

  - visualization: Pose
    reference: /move_base/current_goal
    mqtt_details:
      latched: true
    display_details:
      shape: arrow
      colour: 255,0,0

  - visualization: PoseArray
    reference: /particle_cloud
    display_details:
      shape: arrow_flat  # we should only need this one
      flat_colour: 255,0,0

  - visualization: RobotModel
    reference: /robot_description #we use topic but really this is a param
